global:
  scrape_interval:     36s

scrape_configs:
  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

docker run \
    -p 9090:9090 \
    -v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml \
    prom/prometheus